# Send POST request with body as parameter
# post 방식은 csrf토큰을 검사하기 때문
POST http://localhost:8080/api/login
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "username": "user",
  "password": "1111"
}

###